# Generated by Django 6.0.4 on 2026-04-26 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/covers/"
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("public_slug", models.SlugField(blank=True, unique=True)),
                ("qr_code_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_url", models.ImageField(upload_to="photos/original/")),
                (
                    "thumbnail_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/thumbnails/"
                    ),
                ),
                (
                    "compressed_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/compressed/"
                    ),
                ),
                ("upload_status", models.CharField(default="PENDING", max_length=20)),
                (
                    "processing_status",
                    models.CharField(default="QUEUED", max_length=20),
                ),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
