/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Geist', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica Neue', 'sans-serif'],
        serif: ['EB Garamond', 'Georgia', 'serif'],
        display: ['EB Garamond', 'Georgia', 'serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      colors: {
        background: '#FFFFFF',
        foreground: '#18171C',
        card: '#FFFFFF',
        'card-foreground': '#18171C',
        popover: '#FFFFFF',
        'popover-foreground': '#18171C',
        primary: '#263043',
        'primary-foreground': '#FFFFFF',
        secondary: '#F5F5F5',
        'secondary-foreground': '#18171C',
        muted: '#F5F5F5',
        'muted-foreground': '#898B91',
        accent: '#F5F5F5',
        'accent-foreground': '#18171C',
        destructive: '#481F1E',
        border: '#E4E4E7',
        input: '#E4E4E7',
        ring: '#898B91',
        'deep-slate': '#263043',
        night: '#18171C',
        'rose-mist': '#F4C9C8',
        'sage-green': '#A7C3A8',
        'deep-rose': '#481F1E',
        forest: '#2D492E',
        'steel-gray': '#8C929D',
        charcoal: '#000000',
        coal: '#040406',
        platinum: '#FFFFFF',
        'light-gray': '#EDEEF2',
        'off-white': '#F5F5F5',
        silver: '#E4E4E7',
        stone: '#B2B3BA',
        ash: '#898B91',
        gray: '#9B9B9B',
      },
    },
  },
  plugins: [],
}